apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-simple-config
  namespace: endpoint-stats
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key log
        pattern /error|ERROR|exception|Exception|fail|Fail/
      </regexp>
    </filter>

    <match **>
      @type stdout
    </match>
