# This Secret defines the admin password for Grafana.
# Secrets are the Kubernetes way to store and manage sensitive information,
# such as passwords, OAuth tokens, and ssh keys.
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets  # Name referenced by the Grafana deployment
  namespace: endpoint-stats
type: Opaque  # Generic secret type for arbitrary data
data:
  admin-password: YWRtaW4=  # "admin" in base64 - Should be changed in production
