apiVersion: monitoring.coreos.com/v1
# This file defines a PrometheusRule custom resource, which is supported by the Prometheus Operator.
# The PrometheusRule kind allows you to specify alerting and recording rules for Prometheus in a Kubernetes-native way.
# These rules are automatically discovered and managed by the Prometheus Operator, enabling dynamic and declarative monitoring configurations.
kind: PrometheusRule
metadata:
  name: endpoint-stats-alerts
  namespace: endpoint-stats
spec:
  groups:
  - name: endpoint-stats
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for the last 5 minutes

    - alert: SlowResponseTime
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Slow response times detected
        description: 95th percentile of response time is above 2 seconds for the last 10 minutes

    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="endpoint-stats"}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace="endpoint-stats"}) by (pod) > 0.8
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: Pod {{ $labels.pod }} has been using more than 80% of its CPU limit for 15 minutes
