apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-api
  namespace: endpoint-stats
spec:
  selector:
    matchLabels:
      app: flask-api
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'http_requests_total|http_request_duration_seconds.*|process_.*'
      action: keep
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres
  namespace: endpoint-stats
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
  - port: metrics
    interval: 30s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_number]
      regex: "9187"
      action: keep
