repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: local
    hooks:
    -   id: docker-tests
        name: Run tests in Docker
        entry: ./run_tests.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        types: [python]
        exclude: '^$'  # Run on all files
