apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: endpoint-stats
type: Opaque
data:
  # Base64 encoded credentials - in production these should be managed by a secure vault service
  DB_USER: cG9zdGdyZXM=        # "postgres" in base64
  DB_PASSWORD: cG9zdGdyZXM=    # "postgres" in base64
  REDIS_PASSWORD: ""           # Empty password for development
  API_KEY: ZW5kcG9pbnQtc3RhdHMta2V5  # "endpoint-stats-key" in base64
