apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: endpoint-stats
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
  namespace: endpoint-stats
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]  # Required for service discovery and target scraping
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["prometheus-config", "prometheus-rules"]  # Only access relevant ConfigMaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespace: endpoint-stats
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: endpoint-stats
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
