apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-stats-sa
  namespace: endpoint-stats
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoint-stats-reader
  namespace: endpoint-stats
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]  # Read-only access to pod and service info
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]  # Read-only access to ConfigMaps
  resourceNames: ["api-config"]  # Limit to specific ConfigMap
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]  # Needed for service discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-stats-reader-binding
  namespace: endpoint-stats
subjects:
- kind: ServiceAccount
  name: endpoint-stats-sa
  namespace: endpoint-stats
roleRef:
  kind: Role
  name: endpoint-stats-reader
  apiGroup: rbac.authorization.k8s.io
