# This file defines Kubernetes Secrets for the Endpoint Statistics application.
# Secrets are used to store sensitive information like passwords, tokens, and keys
# separately from the application code, improving security and configuration management.
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: endpoint-stats
  labels:
    app: endpoint-stats
    type: credentials
  annotations:
    description: "Consolidated secret for DB, Redis, and API credentials."
type: Opaque
data:
  # Base64 encoded credentials - in production, these should be generated securely
  DB_USER: cG9zdGdyZXM=        # "postgres" in base64
  DB_PASSWORD: cG9zdGdyZXM=    # "postgres" in base64
  REDIS_PASSWORD: ""           # Empty password for development
  API_KEY: ZW5kcG9pbnQtc3RhdHMta2V5  # "endpoint-stats-key" in base64
