# This file defines Kubernetes Secrets for the Endpoint Statistics application.
# Secrets are used to store sensitive information like passwords, tokens, and keys
# separately from the application code, improving security and configuration management.
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-api-secret  # Name referenced by the Flask API deployment
  namespace: endpoint-stats
type: Opaque  # Generic secret type for arbitrary data
data:
  # Base64 encoded credentials - in production, these should be generated securely
  DB_USER: dXNlcg==      # "user" in base64
  DB_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
