apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: endpoint-stats
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:14
            command: ["/bin/sh", "-c"]
            args:
            - |
              pg_dump -h postgres -U admin -d endpoint_stats > /backup/backup-$(date +%Y%m%d).sql

              # Cleanup old backups (keep last 10 days)
              find /backup -name "backup-*.sql" -type f -mtime +10 -delete

              # Log backup completion
              echo "Backup completed at $(date)" >> /backup/backup.log
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
