apiVersion: v1
kind: ServiceAccount
metadata:
  name: maintenance-sa
  namespace: endpoint-stats
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maintenance-role
  namespace: endpoint-stats
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintenance-rolebinding
  namespace: endpoint-stats
subjects:
- kind: ServiceAccount
  name: maintenance-sa
  namespace: endpoint-stats
roleRef:
  kind: Role
  name: maintenance-role
  apiGroup: rbac.authorization.k8s.io
